### ISSUE TITLE
Scala.js support

### ISSUE THREAD

**Issue by mb720** [sksamuel/scrimage#141]
Hi and thanks a lot for your great library!

I was wondering if you had any plans to compile scrimage using Scala.js and publish it so scrimage could run in the browser?

**Comment by gwenzek** [comment]
Hi, I don't think it will work due to the dependency with the java.awt library.

I worked a long time ago [on removing it.](https://github.com/gwenzek/scrimage/tree/Filters)
The main problem is removing the PNG, JPEG readers.
Those also rely on java.awt and are a bit complex to rewrite.

But that would totally be an interesting feature.

**Comment by mb720** [comment]
> The main problem is removing the PNG, JPEG readers.
> Those also rely on java.awt and are a bit complex to rewrite.

I see. Maybe it's easier to rewrite [ImageIO](https://docs.oracle.com/javase/8/docs/api/javax/imageio/ImageIO.html) instead.

**Comment by sksamuel** [comment]
As @gwenzek says, to use this project in scala.js would require porting the entire AWT library, which is a huge undertaking, and one that's extremely unlikely to happen as part of this project. We did kind of expore it briefly, but when we realized just how much work would be involved, it never progressed.
Therefore I'm going to close this issue.
