### ISSUE TITLE
requirement failed

### ISSUE THREAD

**Issue by BruceWouaigne** [sksamuel/scrimage#154]
Hi there. I'm getting a `java.lang.IllegalArgumentException: requirement failed` while doing

    val input: InputStream = new URL(imageUrl).openStream()
    val image: Image = Image.fromStream(input)

    image
      .scaleTo(254, 254)
      .toString()

Am I doing something wrong?

(I'm using scrimage-core 2.1.8)

Thanks

**Comment by sksamuel** [comment]
Do you have the full stack trace?

**Comment by ktuukkan** [comment]
Hi! Thanks for the awesome library! I'm also experiencing the same issue with streams obtained from URLs. Sometimes it may work, but most often it just throws.

I think the problem is in the `Image.fromStream(InputStream)` where you require the given stream not to be `null` and `available()` to return value greater than 0. The latter seems wrong as the _currently available_ zero bytes does not necessarily imply zero total length.

From the javadocs:

> Note that while some implementations of InputStream will return the total number of bytes in the stream, many will not. It is never correct to use the return value of this method to allocate a buffer intended to hold all data in this stream.
> The available method for class InputStream always returns 0.

(https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#available--)

Hope this helps :)

**Comment by yeonhoo** [comment]
Since available method for class InputStream always returns 0, it always fails in `require(in.available > 0)` from `def fromStream` method. 

The workaround would be either 
1) overriding the method `available()` by subclassing InputStream or
2) manually set a value 

I don't know if it is possible to manually set a value ( value > 0). I'm going to be back to give you feedback

**Comment by aturner-tvpage** [comment]
Same problem here - simply trying to load an image from a URL inputStream fails.

**Comment by aturner-tvpage** [comment]
You can work around this by loading from AwtImage:
(url: URL) => Image.fromAwt(ImageIO.read(url))

**Comment by sksamuel** [comment]
Release 4.0 no longer requires available > 0
