### ISSUE TITLE
Can't load PNG, JPEG Images with scrimage-webp

### ISSUE THREAD

**Issue by mr-w1lde** [sksamuel/scrimage#245]
I need a scrimage-webp lib for compression, but if I use it, I can't load png or jpg files via `ImmutableImage.loader().fromBytes(receiveBytes)`

The error I've got
<img width="1651" alt="Screenshot 2022-02-23 at 21 33 25" src="https://user-images.githubusercontent.com/44321056/155849800-694efec5-49c5-46e4-8416-d2a6f22e88f3.png">

But if I'll remove the scrimage-webp, when everything is working fine  
 
scrimage version 4.0.27.
OS: MacOS 11.6.2 
AdoptOpenJDK 11

**Comment by sksamuel** [comment]
Can you provide sample code with an image ?

**Comment by mr-w1lde** [comment]
Hi, @sksamuel
![Screenshot 2022-02-26 at 20 30 01](https://user-images.githubusercontent.com/44321056/155853089-003e8c53-cd18-43df-8d24-f8e6eb382140.png)

**Comment by sksamuel** [comment]
Can you a) paste code so I can copy it, and b) make it standalone, and c)
include the offending image.

**Comment by mr-w1lde** [comment]
@sksamuel  
Okay... I'm using ktor to get an image and seding a POST request via Postman 

    install(Routing) {
        post("api/v1/media") {
            val multipartData = call.receiveMultipart()
            val logger = LoggerFactory.getLogger(this::class.java)

            when (val part = multipartData.readPart()) {
                is PartData.FileItem -> {
                    val receiveBytes = part.streamProvider().readBytes()
                    val format = FormatDetector.detect(receiveBytes)
                    logger.info("Image format - {}", format.get().name)
                    val originalImage = ImmutableImage.loader().fromBytes(receiveBytes)

                    val meta = ImageMetadata.fromImage(originalImage)

                    call.respond(meta.tags().toList())
                }
            }
        }
    }
   
 it doesn't work with any png or jpg image. 
   
![2021-04-13 23 16 43](https://user-images.githubusercontent.com/44321056/155854579-9f6e123a-87e8-48e5-a34f-56b0a3353222.jpg)

**Comment by sksamuel** [comment]
This isn't a stand alone test.

You say the issue is with scrimage, but in order for me to test this I have to setup an entire ktor build, and then use an external http client in order to send images in.

What I've done instead is add a test to the webp module that loads the above image using the immutable image loader.
Firstly with the defaults, secondly by specifying webp first.

https://github.com/sksamuel/scrimage/blob/master/scrimage-webp/src/test/kotlin/com/sksamuel/scrimage/webp/Issue245Test.kt

It passes fine. So I guess the issue is external. But if you believe the issue is with the webp handler, then fork this repo, and make that Issue245 test fail like what your are seeing, then I should be able to fix whatever is up.

One thing you can try is copying the input stream to a byte array, because it's probably being scanned twice.

**Comment by mr-w1lde** [comment]
Okay, I will try. Thanks

**Comment by sksamuel** [comment]
I know what you might be seeing.
Are you making a fat jar ?

**Comment by mr-w1lde** [comment]
@sksamuel the second part is working for me. Thanks for your help!

**Comment by sksamuel** [comment]
We got there in the end :)
