### ISSUE TITLE
1 pixel shift in scale function

### ISSUE THREAD

**Issue by igalbenardete** [sksamuel/scrimage#70]
When I use the scale function the images shift 1 pixel to the left-top. For example even if an image is scaled with 1.0 value it becomes different than the original image. Here is an example with the original.jpg and scaled.jpg The first image is the scaled one and the second is the original one. If you open them in different tabs and switch from one to other you will realize the shift at the upper left corner, but you have to look carefully.

![scaled](https://cloud.githubusercontent.com/assets/5873188/5701774/d7f44c5e-9a58-11e4-9575-a97e0c71a8e2.jpg)
![original](https://cloud.githubusercontent.com/assets/5873188/5701775/d7f86884-9a58-11e4-873c-d3f3e97de11a.jpg)

**Comment by gwenzek** [comment]
I also noted this effect when I worked on the scaling method. It was there originally so I reproduced it to match the unittest. I didn't realize that it would actually shift the image up on a 1.0 scaling.

I can fix that. It depends on where you center the pixel when you interpolate. Currently the pixel (0, 0) is centered at (0, 0) instead of (0.5, 0.5).

**Comment by igalbenardete** [comment]
Let me know if you will be able to fix this issue.

**Comment by gwenzek** [comment]
8b60fa4b85c7f32aea088659793a309ed466743b fixes it for the branch on maven (it's a 7 characters commit, if you can't wait for a maven release)

9e0745e3f7bd81fd50981460147f652523f3790b fixes it for the working branch, and changes the unittest images
